export const ACCESS_TOKEN = "ACCESS_TOKEN"
export const SIGNUP = "Sign Up"
export const SINGIN = "Sign In"
export const RESET = "Recover Password"
export const CHANGEPASSWORD = "Change Password"
export const VERIFY = "Verify"
export const EDIT = "Edit"